sudo: false
language: python
install:
- pip install -U tox coveralls
jobs:
  include:
  - stage: test
    python: 3.7.6
    dist: xenial
    sudo: true
    env: TOXENV=py37
    script: travis_wait 30 tox --develop
  - stage: test
    python: 3.7.6
    dist: xenial
    sudo: true
    env: TOXENV=lint
    script: travis_wait 30 tox --develop
  - stage: test
    python: 3.7.6
    sudo: true
    dist: xenial
    env: TOXENV=cov
    script: travis_wait 30 tox --develop
    after_success: coveralls
  - stage: deploy
    script: skip
    python: 3.7.6
    sudo: true
    dist: xenial
    env:
    deploy:
      provider: pypi
      distributions: sdist
      user: jtappolet
      password:
        secure: BIJhWNg1ROr5ujItWX7fJ6w3zbpsrkjDWucVBV6wvDzSHTVjsQFpL7HZZhf/rz2SXiIEjWRggW47lENmLj1VJYMCMZhxzd57xVaRsDouCH1hM+sVAE3N7daWKK3JIPk+T0aJsLUpmOhNfSHrUXToTVRteHEvrsPb0apiYpxFFBLFDmrAXRx3xSrLGyaFxMoG7W8vcTtVlZMCoJ+xFvBmotGxhzjRPXPIt/BLSqnRJl+HHGAITE7E6Lhu0N2KWrEx/ivJwErf9UwfzF3pxAMxYKDjKb1h34p82dG2wkn0mKVgNSKELmdPNaUsdzOkxRhzgLQ5IKRbNxJR60jMRn2b/WfNlhAlCm2rHwUA1pPZB9NWwFRZpz1CokD/bi77Uqq4VbUWs1UkBuUlyVm7IIyJ1MBy4Slv2VmrGwmbsVRDeWTNyG2v0MbgL2O8nS1OowExU6DKIi6wPvaTQtgyaCsKVadOjoki9mWmhlN8pxx2fkM9S1JK4p2iVENGmTy3md5rj0KY8rpMK0MsLet2p85ffwgMLUw8FgVRvG8FsYkD6ifTDrwdFcDRKvvTwP+h6gobFNJCGP3EwCCMxb6uwIqQ3X5P/I0g4M1SxkKnON2Vt5E5McLzVyDLEGx5J9qwb17xMWQdDcNpIylShGA9r08L1NC3qONPPA88+mJ5j37xwdg=
      on:
        tags: true

